### ISSUE TITLE
Todo: Tests

### ISSUE THREAD

**Issue by shealavington** [directus/api-tests#5]
# The following is a list of tests that need to be written to help ensure the API works as expected.

## Tests Status
These tests are somewhat following the structure setout in the docs, if a test is missing from here, feel free to leave a comment on exactly what's missing.

### Authentication

* [ ] Tokens
* [ ] Get Auth Token
* [ ] Refresh Auth Token
* [ ] Password Reset Request
* [ ] Password Reset
* [ ] SSO

### Query Parameters
Realistically, these will take some more testing to ensure correctness, for example, Failtering has different operators and each operator needs to be tested.

* [ ] Metadata
* [ ] Fields
* [ ] Limit
* [ ] Offset
* [ ] Single
* [ ] Sorting
* [ ] Status
* [ ] Filtering
* [ ] Language
* [ ] Search Query
* [ ] Groups
* [ ] Skip Activity Logging
* [ ] Activity Comment

### Items

* [X] Get Item
* [X] Get Multiple Items
* [X] Get All Items
* [X] Create Item
* [X] Create Items
* [X] Update Item
* [X] Update Items
* [X] Delete Item
* [X] Delete Items
* [ ] Get Item Revision
* [ ] Get Item Revisions
* [ ] Revert Item
* [ ] Revert Items?

### System

* [ ] Activity
* [ ] Collections
* [ ] Collection Presets
* [ ] Fields
* [ ] Files
* [ ] Folders
* [ ] Permissions
* [ ] Relations
* [ ] Revisions
* [ ] Roles
* [ ] Settings
* [ ] Users

### Utilities

* [ ] Hash String
* [ ] Match Hashed String
* [ ] Generate Random String

### Mail

* [ ] Send Email

### Extensions

* [ ] Get Extensions
* [ ] Get Interface
* [ ] Get Page
* [ ] Get Custom Endpoint

### Server

* [ ] Information
* [x] Ping

### Projects

* [ ] Information
* [ ] Update
* [ ] Create Project
* [ ] Projects Auth Config
* [ ] Projects CORS Config
* [ ] Projects Cache Config
* [ ] Projects Storage Config
* [ ] Projects Mail Config
* [ ] Projects Rate Limit Config

### Field Types

* [ ] Webhooks

### Directus Objects

* [ ] Activity Object
* [ ] Activity Seen Object
* [ ] Collection Object
* [ ] Collection Preset Object
* [ ] Field Object
* [ ] File Object
* [ ] Folder Object
* [ ] Permission Object
* [ ] Relation Object
* [ ] Revision Object
* [ ] Role Object
* [ ] Setting Object
* [ ] User Object
* [ ] User Role Object

### SCIM

* [ ] Overview
* [ ] Create SCIM User
* [ ] Get SCIM Users
* [ ] Get SCIM User
* [ ] Update SCIM User
* [ ] Create SCIM Group
* [ ] Get SCIM Groups
* [ ] Get SCIM Group
* [ ] Update SCIM Group
* [ ] Delete SCIM Group
